name: Build n Deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    NODE_VERSION: 24.12.0

permissions:
    contents: write

jobs:
    build-n-package:
        name: 'Build & Package'
        runs-on: ubuntu-latest
        steps:
            - name: 'ðŸ“¥ checkout repository'
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: 'ðŸ”§  Setup NodeJS ${{ env.NODE_VERSION }}'
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'yarn'

            - name: 'ðŸ”§ Install dependencies'
              run: yarn install

            - name: 'Run Build'
              run: yarn run build:apps:prod

            - name: 'Package ./apps'
              run: yarn run package:apps

            - name: 'Prepare Dashboard Deps'
              run: yarn run dashboard:deps

            - name: Build Dashboard
              run: yarn run build:dashboard:prod

            - name: 'Package Dashboard'
              run: yarn run package:dashboard

            - name: 'Upload apps artifact'
              uses: actions/upload-artifact@v6
              with:
                  name: package-${{ github.run_number }}-${{ github.run_id }}
                  path: './package/wbk--reactjs-playground'
                  retention-days: 30

    deploy:
        name: 'Deploy to GitHub Pages'
        needs: build-n-package
        runs-on: ubuntu-latest
        steps:
            - name: 'Download apps artifact'
              uses: actions/download-artifact@v7
              with:
                  name: package-${{ github.run_number }}-${{ github.run_id }}
                  path: ./package

            - name: 'Deploy to GitHub Pages'
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./package
